
project_id = "citibygettyzjgaewfca"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://b8422a16-2d1b-4221-8de6-b5e8fc64933f.lovableproject.com", "https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_reuse_interval = 10
enable_signup = false

[auth.email]
enable_signup = false
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true

[functions.setup-demo-users]
verify_jwt = true

[functions.generate-obligation-file]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
