-- Seed do Plano de Contas do cliente Favarini (origem: Favarini Plano de Contas.xlsx, aba 'Sugestão')
-- Aplica para TODAS as organizations existentes. Idempotente via ON CONFLICT no índice único
-- chart_of_accounts_org_name_uniq (org_id, lower(btrim(conta_contabil))).

WITH seed (conta_contabil, grupo, nivel, tipo) AS (
  VALUES
  ('(-) Devoluçao de Vendas', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('(+) Despesas não dedutiveis', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('13º Proporcional', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Adiantamento Cliente', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Adiantamento Fornecedor', 'Custo Fornecedor', 'Custos Diretos', 'Saídas'),
  ('Agua e esgoto', 'Despesa Estrutura', 'Despesas Fixas', 'Saídas'),
  ('Aluguel', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Aporte', 'Outras Entradas', 'Receitas Não Operacionais', 'Entradas'),
  ('Aquisições e investimentos', 'Investimentos', 'Não Operacional', 'Saídas'),
  ('Assistencia a funcionários', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Assistencia a Clientes', 'Despesa Operacional', 'Despesas Variáveis', 'Saídas'),
  ('Associacoes e Entidades', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Bens de Pequeno Valor', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Brindes, doações e patrocinios', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Cofins', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('Combustivel', 'Despesa Operacional', 'Despesas Variáveis', 'Saídas'),
  ('Comissoes de Mecanicos', 'Custo Operacional', 'Custos Diretos', 'Saídas'),
  ('Conaren', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Condenações Judiciais', 'Passivo', 'Não Operacional', 'Saídas'),
  ('Conserv. Manut. Imovel', 'Despesa Estrutura', 'Despesas Fixas', 'Saídas'),
  ('Consórcios', 'Investimentos', 'Não Operacional', 'Saídas'),
  ('Copa e Cozinha', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Correios', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('CSll', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('Cursos e Treinamentos', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Custa Judiciais', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Despesas com Internet', 'Despesa Estrutura', 'Despesas Fixas', 'Saídas'),
  ('Despesas Com Viagens', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Distribuição de Lucro', 'Distribuição de Lucro', 'Não Operacional', 'Saídas'),
  ('Doação', 'Distribuição de Lucro', 'Não Operacional', 'Saídas'),
  ('Emprestimos', 'Empréstimo (Entrada)', 'Receitas Não Operacionais', 'Entradas'),
  ('Emprestimos Obtidos', 'Empréstimo (Entrada)', 'Receitas Não Operacionais', 'Entradas'),
  ('Energia Eletrica', 'Despesa Estrutura', 'Despesas Fixas', 'Saídas'),
  ('Estoque Bombas Injetoras', 'Custo Fornecedor', 'Custos Diretos', 'Saídas'),
  ('Férias', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Ferramentas', 'Despesa Operacional', 'Despesas Variáveis', 'Saídas'),
  ('FGTS a recolher', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Fretes', 'Custo Operacional', 'Custos Diretos', 'Saídas'),
  ('Honorários Advocaticios', 'Despesa Com Terceiros', 'Despesas Fixas', 'Saídas'),
  ('Honorarios Contabeis', 'Despesa Com Terceiros', 'Despesas Fixas', 'Saídas'),
  ('Hospedagem', 'Despesa Operacional', 'Despesas Variáveis', 'Saídas'),
  ('ICMS', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('Indenizacao Trabalhista', 'Passivo', 'Não Operacional', 'Saídas'),
  ('INSS a recolher', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Investimento em Construções e Reformas', 'Investimentos', 'Não Operacional', 'Saídas'),
  ('IOF', 'Despesa Financeira', 'Não Operacional', 'Saídas'),
  ('IPVA', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('IR Retido na Fonte', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('IRPJ', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('IRRF', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('ISSQN a recolher', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('Juros Emprestimos', 'Despesa Financeira', 'Não Operacional', 'Saídas'),
  ('Juros pagos', 'Despesa Financeira', 'Não Operacional', 'Saídas'),
  ('Juros Recebidos', 'Outras Entradas', 'Receitas Não Operacionais', 'Entradas'),
  ('Lanches, Refeições e Entretenime', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Locação de Impressoras', 'Despesa Estrutura', 'Despesas Fixas', 'Saídas'),
  ('Lubrificantes', 'Custo Fornecedor', 'Custos Diretos', 'Saídas'),
  ('Manutenção de Veículos', 'Despesa Operacional', 'Despesas Variáveis', 'Saídas'),
  ('Manutenção em Computadores', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Manutenção em Redes', 'Despesa Estrutura', 'Despesas Fixas', 'Saídas'),
  ('Manutencao Maquinas Ferram. e Eq', 'Despesa Operacional', 'Despesas Variáveis', 'Saídas'),
  ('Manutenção Predial', 'Despesa Estrutura', 'Despesas Fixas', 'Saídas'),
  ('Maquinas e Ferramentas', 'Despesa Operacional', 'Despesas Variáveis', 'Saídas'),
  ('Materiais de Escritorio', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Material de Informatica', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Material de Limpeza', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Medicina e Segurança do Trabalho', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Mercadorias', 'Custo Fornecedor', 'Custos Diretos', 'Saídas'),
  ('Multas Recebidas', 'Outras Entradas', 'Receitas Não Operacionais', 'Entradas'),
  ('Peças Ciclo Diesel', 'Custo Fornecedor', 'Custos Diretos', 'Saídas'),
  ('Peças Ciclo Otto', 'Custo Fornecedor', 'Custos Diretos', 'Saídas'),
  ('Pedagio', 'Despesa Operacional', 'Despesas Variáveis', 'Saídas'),
  ('PIS', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('Plano de Saude', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Plano Odontologico', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Prolabore', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Propaganda e Publicidade', 'Despesa Comercial/Marketing', 'Despesas Variáveis', 'Saídas'),
  ('Receitas RSFD', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Reembolso de despesas', 'Custo Operacional', 'Custos Diretos', 'Saídas'),
  ('Refeições', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Rendimento de Aplicação', 'Rendimento', 'Receitas Não Operacionais', 'Entradas'),
  ('Rescisão', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Salarios', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Seguro de Vida', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Seguros cartões', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Serviços Administrativos', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Serviços de Terceiros', 'Despesa Com Terceiros', 'Despesas Fixas', 'Saídas'),
  ('Simples Nacional', 'Impostos', 'Custos Diretos', 'Saídas'),
  ('Sindicato', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Software', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Tarifas Administrativas', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Tarifas Financeiras', 'Despesa Financeira', 'Não Operacional', 'Saídas'),
  ('Tarifas Operacionais', 'Custo Operacional', 'Custos Diretos', 'Saídas'),
  ('Taxas e Emolumentos', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas'),
  ('Telefone', 'Despesa Estrutura', 'Despesas Fixas', 'Saídas'),
  ('Transferencia entre contas', 'Transferência', NULL, NULL),
  ('Uniformes e EPIs', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Uso e Consumo Prestação Serviços', 'Despesa Operacional', 'Custos Diretos', 'Saídas'),
  ('Vale Alimentação', 'Despesa com Pessoal', 'Despesas Fixas', 'Saídas'),
  ('Venda de Peças Motores a Diesel', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Venda de Peças Motores Flex', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Venda de Serviços Motores Diesel', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Venda de Serviços Motores Flex', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Venda Oleo Usado', 'Outras Entradas', 'Receitas Não Operacionais', 'Entradas'),
  ('Vendas de Peças Varejo a prazo', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Vendas de Peças Varejo a Vista', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Vendas de Serviços a Prazo', 'Faturamento', 'Receitas Operacionais', 'Entradas'),
  ('Vigilancia e Segurança', 'Despesa Administrativa', 'Despesas Variáveis', 'Saídas')
)
INSERT INTO public.chart_of_accounts (org_id, conta_contabil, grupo, nivel, tipo, is_active)
SELECT o.id, s.conta_contabil, s.grupo, s.nivel, s.tipo, true
FROM public.organizations o
CROSS JOIN seed s
WHERE NOT EXISTS (
  SELECT 1 FROM public.chart_of_accounts coa
  WHERE coa.org_id = o.id
    AND lower(btrim(coa.conta_contabil)) = lower(btrim(s.conta_contabil))
);
